### ISSUE TITLE
Не работает :(

### ISSUE THREAD

**Issue by FlameProfi** [07artem132/whmcs-notifications-telegram-integration#2]
Whoops\Exception\ErrorException: require(): Failed opening required '/var/www/billing.pastaex.fun/modules/notifications/Telegram/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/billing.pastaex.fun/modules/notifications/Telegram/Telegram.php:11
Stack trace:
#0 /var/www/billing.pastaex.fun/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError()
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}

**Comment by 07artem132** [comment]
Вам необходимо скачать "composer.phar" в директорию с проектом, а затем выполнить php composer.phar install.
Скачать composer можно с официального сайта: https://getcomposer.org/

**Comment by FlameProfi** [comment]
Я пытался его установить, но мне написала что он для более ранних версий php

**Comment by 07artem132** [comment]
Прикрепите пожалуйста все сообщение которое писало.
